AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'db/schema.rb'
inherit_from: .rubocop_todo.yml
inherit_gem:
  rubocop-config-prettier: config/rubocop.yml
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'db/schema.rb'
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/DoubleNegation:
  Enabled: false