version: "3"

services:
  app:
    build: .

    command: ruby app.rb -o 0.0.0.0

    ports:
      - "3000:4567"

    volumes:
      - .:/app
      - app-bundle:/usr/local/bundle
volumes:
  app-bundle: